"""Alembic migration script template.

Revision ID: 0357b31ed0fa
Revises: 283e0203248d
Create Date: 2026-04-15 22:45:01.943323

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0357b31ed0fa'
down_revision = '283e0203248d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
