"""Alembic migration script template.

Revision ID: 1aecf0df27a8
Revises: drop_employment_info
Create Date: 2026-04-15 23:16:15.281044

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1aecf0df27a8'
down_revision = 'drop_employment_info'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('office_department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('employees', sa.Column('position_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('employees', sa.Column('employment_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.drop_column('employees', 'employee_type')
    op.drop_column('employees', 'position')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'office')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('office', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('employee_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('employees', 'employment_status')
    op.drop_column('employees', 'position_title')
    op.drop_column('employees', 'office_department')
    # ### end Alembic commands ###
