"""Alembic migration script template.

Revision ID: 283e0203248d
Revises: 
Create Date: 2026-04-15 22:21:19.309142

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '283e0203248d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_information',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('name_extension', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('civil_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('blood_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('citizenship', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('house_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('subdivision_village', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('barangay', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_information',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone_no', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('mobile_no', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email_address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basic_information_id')
    )
    op.create_table('employees',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('employee_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('office', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('employee_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('date_hired', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no')
    )
    op.create_table('employment_information',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('office_department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('employment_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basic_information_id')
    )
    op.create_table('government_ids',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id_value', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issuing_body', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('certificate_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_records')
    op.drop_table('government_ids')
    op.drop_table('employment_information')
    op.drop_table('employees')
    op.drop_table('contact_information')
    op.drop_table('addresses')
    op.drop_table('basic_information')
    # ### end Alembic commands ###
