"""Alembic migration script template.

Revision ID: 4327836899d0
Revises: d2a0b5f4e87c
Create Date: 2026-04-19 13:09:33.786524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4327836899d0'
down_revision = 'd2a0b5f4e87c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'step_increment')
    op.drop_column('employees', 'salary_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary_grade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('step_increment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
