"""Alembic migration script template.

Revision ID: 4f6da471d36f
Revises: 1aecf0df27a8
Create Date: 2026-04-15 23:33:46.018029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4f6da471d36f'
down_revision = '1aecf0df27a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_information', sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'basic_information', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(op.f('employees_basic_information_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'basic_information_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('basic_information_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employees_basic_information_id_fkey'), 'employees', 'basic_information', ['basic_information_id'], ['id'])
    op.drop_constraint(None, 'basic_information', type_='foreignkey')
    op.drop_column('basic_information', 'employee_id')
    # ### end Alembic commands ###
