"""Alembic migration script template.

Revision ID: 863f9f1e927c
Revises: 4327836899d0
Create Date: 2026-04-19 13:22:38.317335

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '863f9f1e927c'
down_revision = '4327836899d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_no', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_no')
    # ### end Alembic commands ###
