"""Alembic migration script template.

Revision ID: b203a463bf09
Revises: d2f05d8481d1
Create Date: 2026-04-19 21:02:39.703624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b203a463bf09'
down_revision = 'd2f05d8481d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table exists to avoid errors during potential future resets
    inspector = sa.inspect(op.get_context().bind)
    existing_tables = inspector.get_table_names()
    
    if "training_requests" not in existing_tables:
        op.create_table(
            "training_requests",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("employee_id", sa.String(), nullable=False),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("training_type", sa.String(length=100), nullable=False),
            sa.Column("provider", sa.String(length=255), nullable=False),
            sa.Column("venue", sa.String(length=255), nullable=False),
            sa.Column("date_from", sa.Date(), nullable=False),
            sa.Column("date_to", sa.Date(), nullable=False),
            sa.Column("estimated_cost", sa.Float(), nullable=False),
            sa.Column("number_of_hours", sa.Integer(), nullable=False, server_default=sa.text("0")),
            sa.Column("justification", sa.String(), nullable=False),
            sa.Column("status", sa.String(), nullable=False),
            sa.Column("remarks", sa.String(), nullable=True),
            sa.Column("submitted_at", sa.DateTime(), nullable=False),
            sa.Column("reviewed_at", sa.DateTime(), nullable=True),
            sa.Column("reviewed_by", sa.String(), nullable=True),
            sa.Column("training_event_id", sa.String(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("deleted_at", sa.DateTime(), nullable=True),
            sa.Column("is_deleted", sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(["employee_id"], ["employees.id"]),
            sa.ForeignKeyConstraint(["training_event_id"], ["training_events.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
    else:
        # If table exists, ensure the new columns from migrate_training.py are present
        columns = [c["name"] for c in inspector.get_columns("training_requests")]
        if "number_of_hours" not in columns:
            op.add_column("training_requests", sa.Column("number_of_hours", sa.Integer(), nullable=False, server_default=sa.text("0")))
        if "training_event_id" not in columns:
            op.add_column("training_requests", sa.Column("training_event_id", sa.String(), nullable=True))
            op.create_foreign_key("fk_training_requests_event_id", "training_requests", "training_events", ["training_event_id"], ["id"])

    # Fix relationship server default issue on family_details if detected
    op.alter_column('family_details', 'relationship',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_requests")
    
    op.alter_column('family_details', 'relationship',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Other'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
