"""Alembic migration script template.

Revision ID: c84eed20c377
Revises: fe0f23761ca5
Create Date: 2026-04-23 06:38:30.598256

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c84eed20c377'
down_revision = 'fe0f23761ca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civil_service_eligibilities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('career_service', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_of_examination', sa.Date(), nullable=False),
    sa.Column('place_of_examination', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('license_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date_of_validity', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('training_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('number_of_hours', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('training_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('conducted_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voluntary_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('organization_address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('number_of_hours', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('basic_information_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('monthly_salary', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('salary_grade', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status_of_appointment', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('government_service', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience_records')
    op.drop_table('voluntary_records')
    op.drop_table('training_records')
    op.drop_table('civil_service_eligibilities')
    # ### end Alembic commands ###
