"""Alembic migration script template.

Revision ID: d2f05d8481d1
Revises: fc51c3f3bc62
Create Date: 2026-04-19 17:58:51.505792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd2f05d8481d1'
down_revision = 'fc51c3f3bc62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_details', sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='Other'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_details', 'relationship')
    # ### end Alembic commands ###
