"""Alembic migration script template.

Revision ID: f87cfafcd92a
Revises: b203a463bf09
Create Date: 2026-04-20 01:46:26.079810

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f87cfafcd92a'
down_revision = 'b203a463bf09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary_grade', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('step_increment', sa.Integer(), nullable=True))
    op.alter_column('family_details', 'relationship',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('training_requests', 'number_of_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.create_foreign_key(None, 'training_requests', 'training_events', ['training_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_requests', type_='foreignkey')
    op.alter_column('training_requests', 'number_of_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('family_details', 'relationship',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Other'::character varying"),
               existing_nullable=False)
    op.drop_column('employees', 'step_increment')
    op.drop_column('employees', 'salary_grade')
    # ### end Alembic commands ###
