"""Alembic migration script template.

Revision ID: fc51c3f3bc62
Revises: 863f9f1e927c
Create Date: 2026-04-19 15:21:29.527691

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fc51c3f3bc62'
down_revision = '863f9f1e927c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
