"""Alembic migration script template.

Revision ID: fe0f23761ca5
Revises: f87cfafcd92a
Create Date: 2026-04-22 09:02:39.993083

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe0f23761ca5'
down_revision = 'f87cfafcd92a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column as nullable first
    op.add_column('employees', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # Update existing records to 'pending'
    op.execute("UPDATE employees SET status = 'pending'")
    # Now set it to NOT NULL
    op.alter_column('employees', 'status', nullable=False)
    
    op.add_column('employees', sa.Column('verified_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('employees', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # Keeping other autogenerated changes for consistency
    op.alter_column('training_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'president', 'hr', 'hr-assistant', 'employee', name='user_role'),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'president', 'hr', 'hr-assistant', 'employee', name='user_role'),
               server_default=sa.text("'employee'::user_role"),
               nullable=False)
    op.alter_column('training_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('employees', 'verified_at')
    op.drop_column('employees', 'verified_by')
    op.drop_column('employees', 'status')
    # ### end Alembic commands ###
